### ISSUE TITLE
Form Generator crashes upon rendering full Contracts

### ISSUE THREAD

**Issue by discochance** [accordproject/concerto-ui#22]
**Describe the bug**
Selecting an asset extending AccordContract to be rendered crashes the Form generator
**To Reproduce**
Load following Model ([fragile-goods](https://templates.accordproject.org/fragile-goods@0.13.0.html)) and select "FragileGoodsClause" as FQN.

namespace io.clause.demo.fragileGoods

```import org.accordproject.cicero.contract.* from https://models.accordproject.org/cicero/contract.cto
import org.accordproject.cicero.runtime.* from https://models.accordproject.org/cicero/runtime.cto
import org.accordproject.time.Duration from https://models.accordproject.org/v2.0/time.cto
import org.accordproject.money.MonetaryAmount from https://models.accordproject.org/money.cto

/**
 * The template model
 */
asset FragileGoodsClause extends AccordContract {
  o AccordParty buyer
  o AccordParty seller
  o MonetaryAmount deliveryPrice
  o Double accelerationMin
  o Double accelerationMax
  o MonetaryAmount accelerationBreachPenalty
  o Duration deliveryLimitDuration
  o MonetaryAmount lateDeliveryPenalty
}
```

**Expected behavior**
The Form generator should render a form, allowing the user to fill in all data needed for the contract.

**Additional context**
Testet on concerto-ui-react-demo and similar own implementation. Possibly because of Issue #9 as the Error Message is identical.

**Comment by jeromesimeon** [comment]
This will need more investigation, but those definitely inherits relationships for parties from `AccordContract`:
https://models.accordproject.org/cicero/contract.html

**Comment by mttrbrts** [comment]
Hi @discochance, thanks for reporting the issue. I made some improvements in this area recently, can you confirm which version of the library are you using, please?

I'm not able to replicate with v0.82.7 of the demo app. 🤔

**Comment by discochance** [comment]
Hi, sorry I overlooked the update, I tried the new version and it does fix the problem. Had been trying to work this out for the last few weeks...

**Comment by mttrbrts** [comment]
No problem, I'm glad that this fixed your problem! Let us know what you build!
