### ISSUE TITLE
Add support for read-only rendering

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto-ui#45]
It would be very useful to be able to render a form (or other similar HTML view) that was read-only. This would allow people to use this component to summarise the values of JSON data that was governed by a Concerto model.

**Describe the solution you'd like**
A new prop `readOnly` that could be set on the form component. When true all the fields in the form would read-only (i.e. labels or disabled input fields).

**Comment by kanav-raina** [comment]
hi @dselman, I think for this I need to add readOnly property to both json component and form component because if you change the json component, form component also changes.

**Comment by jolanglinais** [comment]
Is this resolved with #54 @mttrbrts @dselman?

**Comment by mttrbrts** [comment]
> Is this resolved with #54 @mttrbrts @dselman?

Yes
