### ISSUE TITLE
Dark Version of Concerto-UI

### ISSUE THREAD

**Issue by kanav-raina** [accordproject/concerto-ui#46]
Bright white screen causes digital eye strain.

Describe the solution you'd like
Add a dark mode feature to concerto-ui

Why Dark Mode?
- Dark Mode prolongs battery life.
- It looks amazing.
![dark](https://user-images.githubusercontent.com/29794748/77325732-ccd2fa00-6d3e-11ea-9bc8-7ad647573d47.gif)

**Comment by kanav-raina** [comment]
hello @mttrbrts , @irmerk and @jeromesimeon ,
I have added this dark mode feature.

**Comment by jolanglinais** [comment]
@Michael-Grover @mttrbrts wondering if this is useful.

**Comment by Michael-Grover** [comment]
@irmerk I don't think it's totally necessary but I don't have much of an opinion on it, as long as it doesn't affect how the default light mode looks.

**Comment by mttrbrts** [comment]
I added a comment in your PR, https://github.com/accordproject/concerto-ui/pull/47#issuecomment-603224844

Instead of making changes to the demo app, a sample that demonstrates how to add custom classes through `options` / modify the semantic-ui styling would be helpful?

**Comment by kanav-raina** [comment]
Should I close this or work on it? @mttrbrts 
If you want I  can create 
a class and after toggle it will change by using this  https://github.com/accordproject/concerto-ui/blob/fe016997eb518ab5b2f03f49217d9c1e188eea67/packages/concerto-ui-react/src/concertoForm.js#L48    to add dark mode
