### ISSUE TITLE
Logo Missing and Invalid Logo Link 

### ISSUE THREAD

**Issue by kanav-raina** [accordproject/concerto-ui#48]
**Describe the bug**
 Logo is not displaying in title bar 

**To Reproduce**
1. Go to 'concerto-ui/packages/concerto-ui-react-demo/public/index.html'
2. Click on https://accordproject.github.io/concerto/latest/favicon.ico
3. Now go to the provided link'
4. You will get this error page

**Expected behavior**
Logo should be displayed on titlebar

**Screenshots**
![broken_link_in_index_html_file](https://user-images.githubusercontent.com/29794748/77463695-0afa1780-6e2c-11ea-8ba6-de5c80c2f62b.png)

![broken_github_page](https://user-images.githubusercontent.com/29794748/77464108-b1461d00-6e2c-11ea-98b3-89399896e5cb.png)

**Comment by kanav-raina** [comment]
Kindly check this @irmerk and @mttrbrts.
I was not able to change the logo from here but I can add logo through concerto-ui/packages/concerto-ui-react-demo/src/index.html

**Comment by kanav-raina** [comment]
I think to add logo in ConcertoUI, I just add the following in head tag to "concerto-ui/packages/concerto-ui-react-demo/src/index.html" 

`<link rel="shortcut icon" href="https://avatars0.githubusercontent.com/u/29445438?s=200&v=4" >`
Should I add logo in title bar to concerto-ui? @irmerk

**Comment by kanav-raina** [comment]
Concerto-Ui with logo
![concerto_with_logo](https://user-images.githubusercontent.com/29794748/77534280-578e3300-6ebe-11ea-9b44-24cd34df7cdc.png)

Concerto-Ui without logo
![concerto_without_logo](https://user-images.githubusercontent.com/29794748/77534318-6d035d00-6ebe-11ea-8dd8-2649f4cd3db8.png)

**Comment by jolanglinais** [comment]
@mttrbrts pinging you on this.
