### ISSUE TITLE
Models with relationships crash form generator

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto-ui#9]
**Describe the bug**
Models with relationships crash the form generator.

**To Reproduce**

```
namespace io.clause.order

import org.accordproject.money.MonetaryAmount from https://models.accordproject.org/money@0.2.0.cto

abstract asset Product identified by sku {
  o String sku
  o String name default="Widget"
  o String description optional
  o MonetaryAmount price
}

asset PerishableGoods extends Product {
  o DateTime expiration
}

asset Order identified by orderId {
  o String orderId
  --> Product[] products
}
```

**Expected behavior**
Should generate a form *using a string for a relationship* or an array of strings for relationships that are arrays.

**Comment by mttrbrts** [comment]
@dselman This appears to be fixed by https://github.com/accordproject/concerto-ui/pull/21

Are you happy to close?

![image](https://user-images.githubusercontent.com/7544022/73882320-bd185880-4859-11ea-9d04-2ca4bf83a083.png)
